package:
  name: alchemy-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

test:
  requires:
    - nose
    - nose-timer
    - pymbar
    - openmmtools
    - click
    - netcdf4

  imports:
    - alchemy

about:
  home: https://github.com/choderalab/alchemy
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
