package:
  name: alchemy-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - openmm

  run:
    - python
    - numpy
    - openmm

test:
  requires:
    - nose
    - nose-timer
    - click
    - netcdf4
    - pymbar
    - openmmtools

  imports:
    - alchemy

about:
  home: https://github.com/choderalab/alchemy
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
